app:
  name: crmeb_go
  env: local
  key: '7kgDM7GoR0KngCJEwBIc3bk80v55bJgijXKlRj4wt1k='
server:
  http:
    addr: :8190

log:
  level: info # info error warn
  format: console # console 有颜色  json 无颜色
  prefix: "[test/dazhou]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1


# system configuration
system:
  db-type: mysql
  oss-type: local # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-redis: false # 使用redis
  use-mongo: false     # 使用mongo
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600
  #  路由全局前缀
  router-prefix: ""
  #  严格角色模式 打开后权限将会存在上下级关系
  use-strict-auth: false


mysql:
  path: 'localhost'   # 链接地址
  port: '3306'   # 链接端口
  config: ''  # 其他配置 例如时区
  db-name: 'crmeb'  # 数据库名称
  username: 'root' # 数据库用户名
  password: 'dazhou520' # 数据库密码
  max-idle-conns: 10 # 连接池相关
  max-open-conns: 100 # 连接池相关
  log-mode: "" # 是控制台打印日志级别 "silent"、"error"、"warn"、"info" 不填默认info  填入silent可以关闭控制台日志
  log-zap: false # 日志是否用zap保存到本地
